# Generated by Django 5.0.7 on 2024-08-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_index', models.CharField(db_index=True, max_length=200)),
                ('content_index', models.TextField(db_index=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
